import os
import json
from jinja2 import Template
import datetime

# Simple LLM wrapper: uses environment variables to call real LLM if configured,
# otherwise falls back to a deterministic mock response for offline demo.
class SimpleLLM:
    def __init__(self):
        self.provider = os.environ.get("LLM_PROVIDER")
        self.key = os.environ.get("LLM_API_KEY")

    def generate(self, prompt):
        if self.provider and self.key:
            # Placeholder: integrate real LLM API here (do NOT store keys in code)
            # Example: call Gemini or OpenAI API with self.key
            return "LLM response placeholder. Replace this block with real API integration."
        else:
            # Deterministic mock summary for demo
            return self.mock_generate(prompt)

    def mock_generate(self, prompt):
        # Very small deterministic summary based on keywords found in prompt
        lines = []
        if "revenue_sum" in prompt:
            lines.append("Total revenue observed: summarized in report.")
        if "top_products" in prompt:
            lines.append("Top products identified: see chart.")
        lines.append("Recommendations: investigate anomalies and prioritize high-revenue SKUs.")
        return "\\n".join(lines)

class WriterAgent:
    def __init__(self):
        self.llm = SimpleLLM()

    def write_summary(self, analysis_results, chart_paths):
        print("[Writer] Generating executive summary using LLM (or mock).")
        # Build a prompt
        prompt = json.dumps(analysis_results)
        llm_out = self.llm.generate(prompt)
        # Render a small template
        template = Template(\"\"\"Executive Summary - {{date}}

Overview:
{{llm_out}}

Key Metrics:
- Rows processed: {{row_count}}
- Total revenue: {{revenue_sum}}
- Total units: {{units_sum}}

Charts:
{% for c in charts %}
- {{c}}
{% endfor %}

Generated by ESIA.
\"\"\")
        txt = template.render(
            date=datetime.datetime.utcnow().strftime(\"%Y-%m-%d %H:%M UTC\"),
            llm_out=llm_out,
            row_count=analysis_results.get("row_count"),
            revenue_sum=analysis_results.get("revenue_sum"),
            units_sum=analysis_results.get("units_sum"),
            charts=chart_paths
        )
        # Save to outputs
        os.makedirs("outputs", exist_ok=True)
        with open("outputs/summary.txt", "w") as f:
            f.write(txt)
        return txt
